services:
  - type: web
    name: smart-recipe-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    region: oregon
    branch: main
    buildCommand: ""
    startCommand: ""
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SERVER_PORT
        value: "10000"
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-frontend-domain.com
